# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_age', models.IntegerField()),
                ('applicant_favmmo', models.CharField(max_length=100)),
                ('about_you', models.TextField()),
            ],
        ),
    ]
