# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('d', 'Declined'), ('u', 'Unchecked')], default='u', max_length=1),
        ),
    ]
